version: "3.9"

services:
    mysql:
        image: mysql:8.0.26
        environment:
            MYSQL_ROOT_PASSWORD: my-secret-pw
            MYSQL_DATABASE: mysite
        ports:
            - "3306:3306"
        volumes:
            - mysql_data:/var/lib/mysql


volumes:
    mysql_data:
